//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EUGamesApp {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EUGamesApp.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About Minsk.
        /// </summary>
        internal static string AboutMinsk {
            get {
                return ResourceManager.GetString("AboutMinsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Albania.
        /// </summary>
        internal static string Albania {
            get {
                return ResourceManager.GetString("Albania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Andorra.
        /// </summary>
        internal static string Andorra {
            get {
                return ResourceManager.GetString("Andorra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на App Info.
        /// </summary>
        internal static string AppInfo {
            get {
                return ResourceManager.GetString("AppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Armenia.
        /// </summary>
        internal static string Armenia {
            get {
                return ResourceManager.GetString("Armenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Austria.
        /// </summary>
        internal static string Austria {
            get {
                return ResourceManager.GetString("Austria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Azerbaijan.
        /// </summary>
        internal static string Azerbaijan {
            get {
                return ResourceManager.GetString("Azerbaijan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Belarus.
        /// </summary>
        internal static string Belarus {
            get {
                return ResourceManager.GetString("Belarus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Belgium.
        /// </summary>
        internal static string Belgium {
            get {
                return ResourceManager.GetString("Belgium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bosnia and Herzegovina.
        /// </summary>
        internal static string BosniaAndHerzegovina {
            get {
                return ResourceManager.GetString("BosniaAndHerzegovina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bronze.
        /// </summary>
        internal static string Bronze {
            get {
                return ResourceManager.GetString("Bronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bulgaria.
        /// </summary>
        internal static string Bulgaria {
            get {
                return ResourceManager.GetString("Bulgaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Capital of Belarus.
        /// </summary>
        internal static string Capital {
            get {
                return ResourceManager.GetString("Capital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chizhovka Arena.
        /// </summary>
        internal static string ChizhovkaArena {
            get {
                return ResourceManager.GetString("ChizhovkaArena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Country Name.
        /// </summary>
        internal static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Croatia.
        /// </summary>
        internal static string Croatia {
            get {
                return ResourceManager.GetString("Croatia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cyprus.
        /// </summary>
        internal static string Cyprus {
            get {
                return ResourceManager.GetString("Cyprus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CzechRepublic.
        /// </summary>
        internal static string CzechRepublic {
            get {
                return ResourceManager.GetString("CzechRepublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Denmark.
        /// </summary>
        internal static string Denmark {
            get {
                return ResourceManager.GetString("Denmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dinamo Stadium.
        /// </summary>
        internal static string DinamoStadium {
            get {
                return ResourceManager.GetString("DinamoStadium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Display.
        /// </summary>
        internal static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Estonia.
        /// </summary>
        internal static string Estonia {
            get {
                return ResourceManager.GetString("Estonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EU Places Always Shown.
        /// </summary>
        internal static string EUPlacesAlwaysShown {
            get {
                return ResourceManager.GetString("EUPlacesAlwaysShown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на European Games 2019.
        /// </summary>
        internal static string EuropeanGames {
            get {
                return ResourceManager.GetString("EuropeanGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Falcon Club.
        /// </summary>
        internal static string FalconClub {
            get {
                return ResourceManager.GetString("FalconClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finland.
        /// </summary>
        internal static string Finland {
            get {
                return ResourceManager.GetString("Finland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на France.
        /// </summary>
        internal static string France {
            get {
                return ResourceManager.GetString("France", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Georgia.
        /// </summary>
        internal static string Georgia {
            get {
                return ResourceManager.GetString("Georgia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Germany.
        /// </summary>
        internal static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gold.
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Greece.
        /// </summary>
        internal static string Greece {
            get {
                return ResourceManager.GetString("Greece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hungary.
        /// </summary>
        internal static string Hungary {
            get {
                return ResourceManager.GetString("Hungary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Iceland.
        /// </summary>
        internal static string Iceland {
            get {
                return ResourceManager.GetString("Iceland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ireland.
        /// </summary>
        internal static string Ireland {
            get {
                return ResourceManager.GetString("Ireland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Israel.
        /// </summary>
        internal static string Israel {
            get {
                return ResourceManager.GetString("Israel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Italy.
        /// </summary>
        internal static string Italy {
            get {
                return ResourceManager.GetString("Italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на More Info.
        /// </summary>
        internal static string KnowMore {
            get {
                return ResourceManager.GetString("KnowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kosovo.
        /// </summary>
        internal static string Kosovo {
            get {
                return ResourceManager.GetString("Kosovo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Latvia.
        /// </summary>
        internal static string Latvia {
            get {
                return ResourceManager.GetString("Latvia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Liechtenstein.
        /// </summary>
        internal static string Liechtenstein {
            get {
                return ResourceManager.GetString("Liechtenstein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lithuania.
        /// </summary>
        internal static string Lithuania {
            get {
                return ResourceManager.GetString("Lithuania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Luxembourg.
        /// </summary>
        internal static string Luxembourg {
            get {
                return ResourceManager.GetString("Luxembourg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Macedonia.
        /// </summary>
        internal static string Macedonia {
            get {
                return ResourceManager.GetString("Macedonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Malta.
        /// </summary>
        internal static string Malta {
            get {
                return ResourceManager.GetString("Malta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Map.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Medals.
        /// </summary>
        internal static string Medals {
            get {
                return ResourceManager.GetString("Medals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minsk.
        /// </summary>
        internal static string Minsk {
            get {
                return ResourceManager.GetString("Minsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minsk Arena.
        /// </summary>
        internal static string MinskArena {
            get {
                return ResourceManager.GetString("MinskArena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  is the largest city of Belarus, situated on the Svislač and the Nyamiha Rivers. As the national capital, Minsk has a special administrative status in Belarus and is the administrative centre of Minsk Region (voblasć) and Minsk District (rajon). The population in January 2018 was 1,982,444[1], making Minsk the 11th most populous city in Europe. Minsk is the administrative capital of the Commonwealth of Independent States (CIS) and seat of the Executive Secretary.
        ///
        ///The earliest historical references to Min [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string MinskInfo {
            get {
                return ResourceManager.GetString("MinskInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Moldova.
        /// </summary>
        internal static string Moldova {
            get {
                return ResourceManager.GetString("Moldova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Monaco.
        /// </summary>
        internal static string Monaco {
            get {
                return ResourceManager.GetString("Monaco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Montenegro.
        /// </summary>
        internal static string Montenegro {
            get {
                return ResourceManager.GetString("Montenegro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Netherlands.
        /// </summary>
        internal static string Netherlands {
            get {
                return ResourceManager.GetString("Netherlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Norway.
        /// </summary>
        internal static string Norway {
            get {
                return ResourceManager.GetString("Norway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nothing.
        /// </summary>
        internal static string Nothing {
            get {
                return ResourceManager.GetString("Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Olympic Sports Complex.
        /// </summary>
        internal static string OlympicSportsComplex {
            get {
                return ResourceManager.GetString("OlympicSportsComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Palova-arena.
        /// </summary>
        internal static string PalovaArena {
            get {
                return ResourceManager.GetString("PalovaArena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Places.
        /// </summary>
        internal static string Places {
            get {
                return ResourceManager.GetString("Places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Poland.
        /// </summary>
        internal static string Poland {
            get {
                return ResourceManager.GetString("Poland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Portugal.
        /// </summary>
        internal static string Portugal {
            get {
                return ResourceManager.GetString("Portugal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Radius in walking time.
        /// </summary>
        internal static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Romania.
        /// </summary>
        internal static string Romania {
            get {
                return ResourceManager.GetString("Romania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russia.
        /// </summary>
        internal static string Russia {
            get {
                return ResourceManager.GetString("Russia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на San Marino.
        /// </summary>
        internal static string SanMarino {
            get {
                return ResourceManager.GetString("SanMarino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Serbia.
        /// </summary>
        internal static string Serbia {
            get {
                return ResourceManager.GetString("Serbia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shooting Centre.
        /// </summary>
        internal static string ShootingCentre {
            get {
                return ResourceManager.GetString("ShootingCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Silver.
        /// </summary>
        internal static string Silver {
            get {
                return ResourceManager.GetString("Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Slovakia.
        /// </summary>
        internal static string Slovakia {
            get {
                return ResourceManager.GetString("Slovakia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Slovenia.
        /// </summary>
        internal static string Slovenia {
            get {
                return ResourceManager.GetString("Slovenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spain.
        /// </summary>
        internal static string Spain {
            get {
                return ResourceManager.GetString("Spain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sporting Club.
        /// </summary>
        internal static string SportingClub {
            get {
                return ResourceManager.GetString("SportingClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sports Palace.
        /// </summary>
        internal static string SportsPalace {
            get {
                return ResourceManager.GetString("SportsPalace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sweden.
        /// </summary>
        internal static string Sweden {
            get {
                return ResourceManager.GetString("Sweden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Switzerland.
        /// </summary>
        internal static string Switzerland {
            get {
                return ResourceManager.GetString("Switzerland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tennis Olympic Centre.
        /// </summary>
        internal static string TennisOlympicCentre {
            get {
                return ResourceManager.GetString("TennisOlympicCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timetable.
        /// </summary>
        internal static string Timetable {
            get {
                return ResourceManager.GetString("Timetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turkey.
        /// </summary>
        internal static string Turkey {
            get {
                return ResourceManager.GetString("Turkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ukraine.
        /// </summary>
        internal static string Ukraine {
            get {
                return ResourceManager.GetString("Ukraine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на United Kingdom.
        /// </summary>
        internal static string UnitedKingdom {
            get {
                return ResourceManager.GetString("UnitedKingdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uruchie Sports Palace.
        /// </summary>
        internal static string UruchieSportsPalace {
            get {
                return ResourceManager.GetString("UruchieSportsPalace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zaslavl Regatta Course.
        /// </summary>
        internal static string ZaslavlRegattaCourse {
            get {
                return ResourceManager.GetString("ZaslavlRegattaCourse", resourceCulture);
            }
        }
    }
}
